// <auto-generated />
namespace MvcMoview.Models.ArticleDBMigrationspace
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ArticleDBInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArticleDBInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201307111302490_ArticleDBInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
