// <auto-generated />
namespace MvcMovie.Models.EveApiMigrationspace
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EveApiInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EveApiInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201307211933585_EveApiInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
