// <auto-generated />
namespace EveRevenueTracker.Models.EveApiMigrationspace
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EveApiItemTypeModelAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EveApiItemTypeModelAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201309211401388_EveApiItemTypeModelAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
