// <auto-generated />
namespace MvcMovie.Models.EveApiMigrationspace
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EveApiWalletTablesAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EveApiWalletTablesAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201307172053251_EveApiWalletTablesAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
